---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.30.0@sha256:047357ac0cfea04663786a612ba1eaba9702bef25227a794b52890dd8bcd692e
    # Port forward 8080 to 30443 on the host
    extraPortMappings:
      # Port 30443 on the container
      - containerPort: 30443
        # Port 8080 on the host
        hostPort: 8080
        # TCP protocol
        protocol: TCP
        # Default listen address
        listenAddress: "0.0.0.0"
  - role: worker
    image: kindest/node:v1.30.0@sha256:047357ac0cfea04663786a612ba1eaba9702bef25227a794b52890dd8bcd692e